mysite/artikel/urls.py
from django.urls import path
from django.urls import URLPattern
from .views import artikelIndexView


urlpatterns = [
    path('', artikelIndexView, name = 'index')
]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('<slug:blogslug>', views.show, name = 'show'),
    path('', views.index, name = 'index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import view
from django.conf.urls.static import static
from django.conf import settings
from .view import loginView, logoutView

urlpatterns = [
    path('artikel/',include('artikel.urls')),
    path('about/',view.about,name = 'about'),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', view.index, name='home'),
    path('login/',loginView, name="login"),
    path('logout/',logoutView, name="logout")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/registrasi/urls.py
from django.urls import path
# from . import views

# app_name = "main"   

# urlpatterns = [
#     path("", views.homepage, name="homepage"),
#     path("register", views.register_request, name="register")
# ]
from registrasi.views import register 
 
urlpatterns = [ 
    path('register/', register, name="register"),
] 

mysite/artikel/models.py
from django.db import models

# Create your models here.

mysite/blog/models.py
from contextlib import nullcontext
from django.db import models
from django.utils.text import slugify

class kategori(models.Model):
    nama = models.CharField(max_length=40)
    keterangan = models.TextField(max_length=300)
    slug = models.SlugField(editable=False, blank=True, null=True)

    def save(self):
        self.slug = slugify(self.judul)
        super(kategori, self).save()

    def __str__(self):
        return self.nama

class artikel(models.Model):
    judul = models.CharField(max_length=50)
    isi = models.TextField(max_length=1000, null=True, blank=True)
    tanggal = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    kategori = models.ForeignKey(kategori, on_delete = models.SET_NULL, blank=True, null = True)
    slug = models.SlugField(editable= False, blank= True, null = True)
    gambar = models.ImageField(upload_to = 'media/', blank=True, null= True)

    def save(self):
        self.slug = slugify(self.judul)
        super(artikel, self).save()

    def __str__(self):
        return self.judul

class komen(models.Model):
    artikel = models.ForeignKey(artikel, on_delete=models.SET_NULL, blank= True, null =True)
    tanggal = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    isi = models.TextField(max_length=500, blank= True, null=True)
    email = models.EmailField(max_length=500, blank = True, null=True)
    
def __str__(self):
    return self.email

mysite/registrasi/models.py
from contextlib import nullcontext
from django.db import models
from django.utils.text import slugify

class kategori(models.Model):
    nama = models.CharField(max_length=40)
    keterangan = models.TextField(max_length=300)
    slug = models.SlugField(editable=False, blank=True, null=True)

    def save(self):
        self.slug = slugify(self.judul)
        super(kategori, self).save()

    def __str__(self):
        return self.nama

class artikel(models.Model):
    judul = models.CharField(max_length=50)
    isi = models.TextField(max_length=1000, null=True, blank=True)
    tanggal = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    kategori = models.ForeignKey(kategori, on_delete = models.SET_NULL, blank=True, null = True)
    slug = models.SlugField(editable= False, blank= True, null = True)
    gambar = models.ImageField(upload_to = 'media/', blank=True, null= True)

    def save(self):
        self.slug = slugify(self.judul)
        super(artikel, self).save()

    def __str__(self):
        return self.judul

class komen(models.Model):
    artikel = models.ForeignKey(artikel, on_delete=models.SET_NULL, blank= True, null =True)
    tanggal = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    isi = models.TextField(max_length=500, blank= True, null=True)
    email = models.EmailField(max_length=500, blank = True, null=True)
    
def __str__(self):
    return self.email

mysite/blog/forms.py
from django import forms

class komen_form(forms.Form):
    email = forms.EmailField(
        max_length = 50,
        widget = forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Masukkan email'
            }
        )
    )
    isi = forms.CharField(
        max_length = 50,
        widget = forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Isi Komentar'
            }
        )
    )

mysite/registrasi/forms.py
# from django import forms

# class komen_form(forms.Form):
#     email = forms.EmailField(
#         max_length = 50,
#         widget = forms.TextInput(
#             attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Masukkan email'
#             }
#         )
#     )
#     isi = forms.CharField(
#         max_length = 50,
#         widget = forms.TextInput(
#             attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Isi Komentar'
#             }
#         )
#     )

mysite/artikel/views.py
from django.shortcuts import render

def artikelIndexView(request):
    context = {
        'page_title' :'Artikel',
    }
    return render(request, 'artikel/index.html', context)

mysite/blog/views.py
from dataclasses import dataclass
from multiprocessing import context
from operator import imod
from django.shortcuts import render, redirect
from django.contrib import messages
from . import models
from . import forms

def index(request):
    data_artikel = models.artikel.objects.all().order_by('-id')
    context = {
        'halaman' : 'list artikel',
        'data' : data_artikel,
    }
    return render(request, 'blog/index.html', context)

def show(request, blogslug):
    if request.method == 'POST':
        models.komen.objects.create(
            artikel = models.artikel.objects.get(id=request.POST['kode']),
            email = request.POST['email'],
            isi = request.POST['isi'],
        )
        messages.success(request, 'Komentar disimpan')
        return redirect('blog:show', blogslug)
    data_artikel = models.artikel.objects.get(slug= blogslug)
    data_komen = models.komen.objects.filter(artikel = models.artikel.objects.get(slug = blogslug)).order_by('-id')
    context = {
        'formnya' : forms.komen_form(),
        'halaman' : 'detail artikel',
        'data' : data_artikel,
        'komens' : data_komen
    }
    return render(request, 'blog/show.html', context)

mysite/registrasi/views.py
# import re
# from django.shortcuts import redirect, render
# from django.contrib.auth.forms import UserCreationForm

# def register(request):
#     if(request.method == 'POST'):
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('login')
#     else:
#         form = UserCreationForm()
#     return render(request,'index.html', {'form': form})

# def login(request):
#     return render(request, 'login.html')
from django.shortcuts import render, redirect 
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import UserCreationForm 
 
 
def register(request):
    if(request.method == 'POST'):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request,'register.html', {'form': form})

mysite/artikel/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>
</head>

<body>
    <p>RIsa lestari</p>

</body>

</html>

mysite/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list artikel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>
    {% extends 'layout/base_user.html' %} {% block content%}
    <div class="container-fluid">
        <br />
        <div class="jumbotron" style="margin-top: 50px;">
            <h1 class="display-4 text-center">Hello, berikut ditampilkan project-project Risa!</h1>
            <div class="row row-cols-1 row-cols-md-2 g-4" style="margin-top: 40px;">
                {% for row in data %}
                <div class="col">
                    <div class="card">
                        <img src="{{row.gambar.url}}" class="card-img-top" alt="gambar">
                        <div class="card-body">
                            <h5 class="card-title">{{row.judul}}</h5>
                            <p>{{row.isi}}</p>
                            <p class="card-text"><small class="text-muted">Update at {{row.tanggal}} - {{row.kategori}}</small></p>
                            <a href="{% url 'blog:show' row.slug %}" class="btn btn-block btn-primary">Read more</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endblock content %}
</body>

</html>

mysite/blog/templates/blog/indexanony.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list artikel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>
    {% extends 'layout/base_anonymous.html' %} {% block content%}
    <div class="container-fluid">
        <br />
        <div class="jumbotron">
            <h1 class="display-4 text-center">Hello, {{halaman}}!</h1>
            <div class="row row-cols-1 row-cols-md-2 g-4">
                {% for row in data %}
                <div class="col">
                    <div class="card">
                        <img src="{{row.gambar.url}}" class="card-img-top" alt="gambar">
                        <div class="card-body">
                            <h5 class="card-title">{{row.judul}}</h5>
                            <p>{{row.isi}}</p>
                            <p class="card-text"><small class="text-muted">Update at {{row.tanggal}} - {{row.kategori}}</small></p>
                            <a href="{% url 'blog:show_anonymous' row.slug %}" class="btn btn-block btn-primary">Read more</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endblock content %}
</body>

</html>

mysite/blog/templates/blog/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list artikel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>
    {% extends 'layout/base_user.html' %} {% load static %} {% block content%}
    <div class="container-fluid">
        <br><br>
        <div class="jumbotron">
            <div class="row row-cols-1 row-cols-md-2 g-4">
                <div class="col">
                    <div class="card">
                        <img src="{{data.gambar.url}}" class="card-img-top" alt="gambar">
                        <div class="card-body">
                            <h5 class="card-title">{{data.judul}}</h5>
                            <p>{{data.isi}}</p>
                            <p class="card-text"><small class="text-muted">Update at {{data.tanggal}} - {{data.kategori}}</small></p>
                            <button class="btn btn-danger" onclick="history.go(-1)">Kembali</button>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-header">
                    Tinggalkan komentar
                </div>
                <div class="card-body">
                    {% for message in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <b>{{message}}</b>
                    </div>
                    {% endfor %}
                    <form method="POST" action="{% url 'blog:show' data.slug %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email address</label> {{formnya.email}}
                            <input type="hidden" name="kode" value="{{data.id}}">
                        </div>
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Comment</label> {{ formnya.isi }}
                        </div>

                        <div class="mb-3 form-check">
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <button type="button" class="btn btn-danger">Kembali</button>
                    </form>
                </div>
            </div>
            <br><br>
            <h3>Komentar</h3>
            <br>
            <ul class="list-unstyled ">
                {% for komen in komens %}
                <li class="media">
                    <img class="mr-3" src=" {% static 'img/user.png' %}" width="5%" alt="Generic placeholder image">
                    <br><br>
                    <div class="media-body">
                        <h5 class="mt-0 mb-1">{{komen.email}}</h5>
                        {{komen.isi}}
                        <span class="text-muted">{{komen.tanggal}}</span>
                    </div>
                </li>
                <hr> {% endfor %}
            </ul>


            {% endblock content %}


</body>

</html>

mysite/blog/templates/blog/show_anonymous.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list artikel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>
    {% extends 'layout/base_anonymous.html' %} {% load static %} {% block content%}
    <div class="container-fluid">
        <br />
        <div class="jumbotron">
            <h1 class="display-4 text-center">Hello, !</h1>
            <div class="row row-cols-1 row-cols-md-2 g-4">
                <div class="col">
                    <div class="card">
                        <img src="{{data.gambar.url}}" class="card-img-top" alt="gambar">
                        <div class="card-body">
                            <h5 class="card-title">{{data.judul}}</h5>
                            <p>{{data.isi}}</p>
                            <p class="card-text"><small class="text-muted">Update at {{data.tanggal}} - {{data.kategori}}</small></p>
                            <button class="btn btn-danger" onclick="history.go(-1)">Kembali</button>
                        </div>
                    </div>
                </div>
            </div>


            {% endblock content %}


</body>

</html>

mysite/registrasi/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form method="post" action=".">
        {% csrf_token %} {{form}}
        <input type="submit" value="Sign up">
    </form>
</body>

</html>

mysite/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello World</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>
    {% extends 'layout/base.html' %} {% block content%}
    <div class="container-fluid">
        <br />
        <div class="jumbotron">
            <h1 class="display-4">Hello, {{halaman}}!</h1>
            <p class="lead">{{ deskripsi}}</p>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

mysite/templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello World</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->

</head>

<body>
    {% include 'layout/nav_anonymous.html'%} {% block content %} {% endblock content %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> -->
</body>

</html>

mysite/templates/layout/base_anonymous.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello World</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->

</head>

<body>
    {% include 'layout/nav_anonymous.html'%} {% block content %} {% endblock content %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> -->
</body>

</html>

mysite/templates/layout/base_user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello World</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->

</head>

<body>
    {% include 'layout/nav_user.html'%} {% block content %} {% endblock content %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> -->
</body>

</html>

mysite/templates/layout/nav_anonymous.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Risa's Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <!-- <li>
                        <a href="{% url 'blog:index' %}" class="nav-link">Blog</a>
                    </li> -->
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li> -->
                    <li class="nav_item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</body>

</html>

mysite/templates/layout/nav_user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Risa's Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:index' %}" class="nav-link">Project</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">logout</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</body>

</html>

mysite/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{page_title}}</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Email address</label>
            <input name="username" type="text" class="form-control" id="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input name="password" type="password" class="form-control" id="password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <p>Gunakan username dan password dibawah ini untuk login agar anda bisa menambahkan komentar pada bagian deskripsi project</p>
        <ul>
            <li>
                Username : admin
            </li>
            <li>
                Password : admin12345
            </li>
        </ul>
        <!-- <a href="{% url 'login' %}">Sign up here</a> -->
    </form>
</body>

</html>

mysite/templates/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>
</head>

<body>
    <h1>{{page_title}}</h1>
    <p>Apakah anda yakin mau logout?</p>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="logout" />

    </form>
</body>

</html>